@startuml diagrama-classe
interface AutenticacaoService {
    + login() : void
}
AutenticacaoService <|.. Usuario

abstract class Usuario {
    # nome : String
    # email : String
    # senha : String
    # Usuario(nome : String, email : String, senha : String)
}

class Admin {
    + Admin(...)
}
Usuario <|-- Admin

class MarcadorMedalhas {
    - medalhasOuro : int
    - medalhasPrata : int
    - medalhasBronze : int
    + medalhasTotais() : int
    + medalhasTipo(tipo : EMedalha) : int
    + addMedalha(tipo : EMedalha) : void
    + removerMedalha(tipo : EMedalha) : void
}

abstract class UsuarioOlimpico {
    # marcadorMedalhas : MarcadorMedalhas
    # UsuarioOlimpico(...)
    # {abstract} addMedalha(tipo : EMedalha) : void
    # {abstract} medalhasTotais() : int
    # {abstract} medalhasTipo(tipo : EMedalha) : int
    # {abstract} removerMedalha(tipo : EMedalha) : void
}
UsuarioOlimpico --|> Usuario
UsuarioOlimpico "1" *-- "1" MarcadorMedalhas
Pais --|> UsuarioOlimpico
Atleta --|> UsuarioOlimpico

class Pais {
    - sigla : String
    - atletas : List<Atleta>
    + Pais(..., nome : String, sigla : String)
    + addAtleta(atleta : Atleta) : void
    + removerAtleta(atleta : Atleta) : void
    + listarAtletas() : List<Atleta>
    + filtrarAtletas(condicao : Predicate<Atleta>) : List<Atleta>
    + medalhasTipo(tipo : EMedalha) : int
    + addMedalha(tipo : EMedalha) : void
    + removerMedalha(tipo : EMedalha) : void
}
Olimpiada "1" *-- "*" Pais : participa

class Atleta {
    - pais : Pais
    - equipe : Equipe
    - genero : char
    - InscricaoService : InscricaoService
    - modalidades : List<Modalidade>
    - historicoCompeticoes : List<Competicao>
    + Atleta(...)
    + inscreverCompeticao() : void
    + consultarCompeticoes() : List<Competicao>
    + addMedalha(tipo : EMedalha) : void
    + medalhasTotais() : int
    + medalhasTipo(tipo : EMedalha) : int
    + addMedalha(tipo : EMedalha) : void
    + removerMedalha(tipo : EMedalha) : void
}
Pais "1" o-- "*" Atleta : representa

class Modalidade <<record>>{
    + nome : String
    + descricao : String
    + tipoOlimpiada : ETipoOlimpiada
    + genero : char
    + numAtletas : int
    + duracaoMin : int
    + prorrogacaoMin : int
    + individual : boolean
}
Modalidade "*" o-- "1..*" Atleta : pratica

class GerenciadorTempo {
    - tempoLimiteMin : float
    - decorridoMin : float
    - emProrrogacao : boolean
    - finalizado : boolean
    + GerenciadorTempo(...)
    + pausar() : void
    + retomar() : void
    + prorrogar(tempoExtraMin : float)
}

class Competicao {
    - nome : String
    - modalidade : Modalidade
    - dataHora : LocalDateTime
    - alocadorLocal : AlocadorLocal
    - atletas : List<Atleta>
    - gerenciadorTempo : GerenciadorTempo
    - resultado : Resultado
    + Competicao(...)
    + addAtleta(atleta : Atleta) : void
    + removerAtleta(atleta : Atleta) : void
    + pausar() : void
    + retomar() : void
    + prorrogar() : void
    + finalizar() : void
    + cancelar() : void
    + resultado() : Resultado
}
Competicao "*" --* "1" GerenciadorTempo
Competicao "*" --* "1" Modalidade

class Local {
    - nome : String
    - endereco : String
    - modalidadesSuportadas : List<Modalidade>
    + Local(...)
    + disponivel(dataHora : LocalDateTime) : boolean
    + reservar(competicao : Competicao) : void
}
Local "1..*" o-- "*" Modalidade : suporta

class AlocadorLocal {
    - local : Local
    + AlocadorLocal(...)
    + alocar(competicao : Competicao) : void
}
AlocadorLocal --> Local
AlocadorLocal "1" *-- "1" Competicao

class Resultado {
    - placar : Map<Atleta, Integer>
    - vencedor : Map<Atleta, Integer>
    + Resultado(placar : Map<Atleta, Integer>)
    + getPodio() : Map<Atleta, Integer>
    + getVencedor() : Map<Atleta, Integer>
    + getColocacao(colocacao : int) : Map<Atleta, Integer>
}
Resultado "1" *-- "1" Competicao

enum EMedalha {
    OURO
    PRATA
    BRONZE
}
EMedalha -- MarcadorMedalhas

class Olimpiada {
    - ano : int
    - paises : List<Pais>
    - competicoes : List<Competicao>
    + Olimpiada(ano : int)
    + placarAtual() : Map<Pais, int>
    + listarCompeticoes() : List<Competicao>
    + filtrarCompeticoes(condicao : Predicate<Competicao>) : List<Competicao>
}
Olimpiada "1" *-- "*" Competicao : inclui

enum ETipoOlimpiada {
    VERÃO
    INVERNO
}
ETipoOlimpiada -- Modalidade

@enduml