@startuml diagrama-casos-uso
actor Usuario
actor Admin
actor Tecnico
actor Atleta

usecase "Cadastra Modalidade" as CADASTRA_MODALIDADE
usecase "Cadastra Competição" as CADASTRA_COMPETICAO
usecase "Registra Resultado" as REGRISTRA_RESULTADO
usecase "Entrega Medalha" as ENTREGA_MEDALHA
usecase "Cria Classificação" as CRIA_CLASSIFICACAO
usecase "Cancela Competição" as CANCELA_COMPETICAO

Admin --> CADASTRA_MODALIDADE
Admin --> CADASTRA_COMPETICAO
CADASTRA_COMPETICAO --> (REGRISTRA_RESULTADO) : <<extends>>
CADASTRA_COMPETICAO --> (CANCELA_COMPETICAO) : <<extends>>
REGRISTRA_RESULTADO --> (CRIA_CLASSIFICACAO) : <<include>>
CRIA_CLASSIFICACAO --> (ENTREGA_MEDALHA) : <<include>>

usecase "Faz Cadastro" as FAZ_CADASTRO
usecase "Faz Login" as FAZ_LOGIN

Admin --|> Usuario
Atleta --|> Usuario
Tecnico --|> Usuario

Usuario --> FAZ_LOGIN
FAZ_LOGIN --> (FAZ_CADASTRO) : <<extends>>

usecase "Cadastra Equipe do País" as CADASTRA_EQUIPE
usecase "Remove Atleta" as REMOVE_ATLETA
usecase "Confirma Atleta" as CONFIRMA_ATLETA

Tecnico --> CADASTRA_EQUIPE
CADASTRA_EQUIPE --> (REMOVE_ATLETA) : <<extends>>
CADASTRA_EQUIPE --> (CONFIRMA_ATLETA) : <<extends>>

usecase "Seleciona Equipe do País" as SELECIONA_EQUIPE
usecase "Inscreve-se em Competições" as INSCREVE_COMPETICOES
usecase "Recebe Medalha" as RECEBE_MEDALHA

Atleta --> INSCREVE_COMPETICOES
INSCREVE_COMPETICOES --> (SELECIONA_EQUIPE) : <<include>>
INSCREVE_COMPETICOES --> (RECEBE_MEDALHA) : <<extends>>
@enduml