@startuml diagrama-classe
abstract class Usuario {
    # nome : String
    # email : String
    # senha : String
    # Usuario(nome : String, email : String, senha : String)
    # {abstract} login(email : String, senha : String) : boolean
}

class Admin {
    + Admin(nome : String, email : String, senha : String)
    + login(email : String, senha : String) : boolean
    + cadastrarModalidade(modalidade : Modalidade) : void
    + cadastrarCompeticao(competicao : Competicao) : void
    + cancelarCompeticao(competicao : Competicao) : void
}
Usuario <|-- Admin

interface IMedalha {
    + addMedalha(tipo : EMedalha) : void
    + medalhasTotais() : int
    + medalhasTipo(tipo : EMedalha) : int
}
IMedalha <|.. Pais
IMedalha <|.. Atleta

class Pais {
    - sigla : String
    - atletas : List<Atleta>
    - medalhasOuro : int
    - medalhasPrata : int
    - medalhasBronze : int
    + Pais(..., nome : String, sigla : String)
    + addAtleta(atleta : Atleta) : void
    + removerAtleta(atleta : Atleta) : void
    + addMedalha(tipo : EMedalha) : void
    + medalhasTotais() : int
    + medalhasTipo(tipo : EMedalha) : int
}
Usuario <|-- Pais

class Atleta {
    - pais : Pais
    - equipe : Equipe
    - genero : char
    - modalidades : List<Modalidade>
    - historicoCompeticoes : List<Competicao>
    - medalhasOuro : int
    - medalhasPrata : int
    - medalhasBronze : int
    + Atleta(...)
    + login(email : String, senha : String) : boolean
    + inscreverCompeticao(competicao : Competicao) : void
    + consultarCompeticoes() : List<Competicao>
    + addMedalha(tipo : EMedalha) : void
    + medalhasTotais() : int
    + medalhasTipo(tipo : EMedalha) : int
    + podeParticipar(competicao : Competicao) : boolean
}
Usuario <|-- Atleta
Pais "1" -- "*" Atleta : representa

class Modalidade <<record>>{
    + nome : String
    + descricao : String
    + genero : char
    + numAtletas : int
    + duracaoHoras : float
    + individual : boolean
}
Modalidade -- Admin
Modalidade "*" -- "*" Atleta : participa
@enduml